# Generated by Django 5.2.7 on 2026-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_paper_embedding_model_paper_embedding_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='academic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='expertise',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='journals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='practice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='publication',
            field=models.IntegerField(default=0),
        ),
    ]
