# Generated by Django 5.2.7 on 2026-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_paper_academic_paper_expertise_paper_journals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='source_profile',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='academic',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='journals',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='publication',
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='expertise',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='practice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='publication',
            field=models.IntegerField(default=0),
        ),
    ]
