# Generated by Django 5.2.7 on 2026-08-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_remove_faculty_source_profile_remove_paper_academic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='directory_verified',
            field=models.BooleanField(default=False),
        ),
    ]
