# Generated by Django 5.2.7 on 2026-08-28 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_faculty_directory_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_faculty_name', models.CharField(max_length=255)),
                ('target_department', models.CharField(blank=True, default='', max_length=255)),
                ('target_school', models.CharField(blank=True, default='', max_length=255)),
                ('target_project_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_project_title', models.CharField(blank=True, default='', max_length=500)),
                ('requester_name', models.CharField(blank=True, default='', max_length=255)),
                ('requester_email', models.EmailField(blank=True, default='', max_length=254)),
                ('requester_organization', models.CharField(blank=True, default='', max_length=255)),
                ('requester_role', models.CharField(blank=True, default='', max_length=120)),
                ('shared_keywords', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='new', max_length=16)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_inquiries', to=settings.AUTH_USER_MODEL)),
                ('target_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='academic.faculty')),
            ],
            options={
                'verbose_name_plural': 'network inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
