# Generated by Django 5.2.7 on 2026-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_faculty_institutional_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='school',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
