# Generated by Django 5.2.7 on 2026-08-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_faculty_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='openalex_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='faculty',
            name='orcid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
