# Generated by Django 5.2.7 on 2026-08-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_faculty_openalex_id_faculty_orcid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('github_url', models.URLField(blank=True, default='', max_length=500)),
                ('backend_github_url', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('documentation_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_documentation_url', models.URLField(blank=True, default='', max_length=500)),
                ('documentation_links', models.JSONField(blank=True, default=list)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_3', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'contact settings',
            },
        ),
        migrations.CreateModel(
            name='ContactTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contact_team/')),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
