# Generated by Django 5.2.7 on 2026-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_contactsettings_contactteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='review_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=16),
        ),
    ]
